-- Script SQL para configurar as tabelas de analytics no Supabase
-- Execute este script no SQL Editor do seu projeto Supabase (https://supabase.com/dashboard/project/tonqrfmnpvufuajrmfig/sql)

-- 1. Tabela para registrar visualizações de página
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabela para registrar redimensionamentos (usos da ferramenta)
create table if not exists image_resizes (
  id bigint generated by default as identity primary key,
  format text,
  width int,
  height int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Habilitar Row Level Security (RLS) é uma boa prática
alter table page_views enable row level security;
alter table image_resizes enable row level security;

-- 4. Criar políticas para permitir inserção anônima (qualquer pessoa que acesse o site)
-- Isso é seguro para analytics, pois só permitimos INSERT, não SELECT/UPDATE/DELETE públicos por padrão

create policy "Permitir inserção anônima em page_views" 
on page_views 
for insert 
with check (true);

create policy "Permitir inserção anônima em image_resizes" 
on image_resizes 
for insert 
with check (true);

-- (Opcional) Se quiser ver os dados no painel do Supabase Table Editor sem estar logado como admin (não recomendado para produção),
-- você teria que criar uma policy de SELECT. Mas como você é o admin, você sempre pode ver tudo no dashboard.
